query GetLineageByUID(
    $primaryUid: ID!
    $depthDownstream: Int = 2
    $depthUpstream: Int = 1
    $popularity: [Int!] = [0, 4]
    $biLastUsedDays: Int = 90
    $allowedList: [ID!] = []
  ) {
    lineage(
      primaryUid: $primaryUid
      lineageFilter: {
        depthDownstream: $depthDownstream
        depthUpstream: $depthUpstream
        biLastUsedDays: $biLastUsedDays
        popularity: $popularity
      }
      allowedList: $allowedList
    ) {

      entities {
        __typename

        ...on Table {
          uid
          prop {
            path
          }
          columns {
            prop {
              dbType
              name
              type
              __typename
            }
            uid
            tags {
              name
            }
          }
        }

        ...on DataAppCommon {
          name
        }

        ...on DataAppLookerView {
          name
          columns {
            ...on LookerViewDimension {
              uid
              name
            }
            ...on LookerViewMeasure {
              uid
              name
            }
          }
        }

        ...on DataAppLookerExplore {
          name
          columns {
            ...on LookerViewDimension {
              uid
              name
            }
            ...on LookerViewMeasure {
              uid
              name
            }
          }
        }

        ...on DataAppLookerLook {
          name
          columns {
            ...on LookerViewDimension {
              uid
              name
            }
            ...on LookerViewMeasure {
              uid
              name
            }
          }
        }
      }

      edges {
        sourceUid
        destinationUid
      }
    }
  }

