query GetTableByPath($path: String) {
  table(path: $path) {
    uid
    columns {
      prop {
        name
        number
      }
      usageStats{
        userName
        count
      }
    }
  }
}
